export const CREDIT_TYPES = {

    WELCOME_BONUS: "WELCOME_BONUS",

    SESSION_PAYMENT: "SESSION_PAYMENT",

    SESSION_EARNING: "SESSION_EARNING",

    REFUND: "REFUND",

    ADMIN_REWARD: "ADMIN_REWARD",

};