export const SKILL_CATEGORIES = [
    "Programming",
    "Web Development",
    "Mobile Development",
    "AI & Machine Learning",
    "Data Science",
    "Cloud Computing",
    "Cybersecurity",
    "DevOps",
    "UI/UX Design",
    "Databases",
    "Graphic Design",
    "Soft Skills",
    "Video Editing",
    "Marketing",
    "Business",
    "Finance",
    "Languages",
    "Photography",
    "Content Writing",
    "Communication",
    "Career Development",
    "Other",
];